# Generated by Django 5.2.17 on 2026-09-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
