# Generated by Django 5.2.17 on 2026-10-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SHOPPING', 'Shopping'), ('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
