# Generated by Django 5.2.17 on 2026-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('READ_ONLY', 'Read-Only'), ('CUSTOMER', 'Customer')], max_length=20, unique=True),
        ),
    ]
