# Generated by Django 5.2.17 on 2026-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("django", "Django"), ("fastapi", "FastAPI")],
                        default="django",
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_time_ms", models.FloatField()),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="apilog_created_idx"),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="apilog_status_created_idx",
                    ),
                ],
            },
        ),
    ]
